add_newline = true

[directory]
truncation_symbol = "…/"

[git_branch]
symbol = "\ue702 " # Nerdfont 3.0: nf-md-git

[git_status]
disabled = true

[hg_branch]
disabled = false
truncation_symbol = "…"

[rust]
symbol = "\ue7a8 " # Nerdfont 3.0: nf-dev-rust
