add_newline = true

[custom.jj]
command = '''
jj --no-pager log --revisions @ --limit 1 --ignore-working-copy --no-graph --color always  -T '
separate(" ",
	change_id.shortest(),
	if(conflict, "conflict"),
	if(divergent, "divergent"),
	if(hidden, "hidden"),
)
'
'''
detect_folders = [".jj"]
symbol = "🍐"

[directory]
truncation_symbol = "…/"

[git_branch]
symbol = "\ue702 " # Nerdfont 3.0: nf-md-git

[git_status]
disabled = true

[gradle]
symbol = "\ue660 " # Nerdfont 3.0: nf-seti-gradle

[hg_branch]
disabled = false
truncation_symbol = "…"

[java]
symbol = "\ue738 " # Nerdfont 3.0: nf-dev-java

[python]
symbol = "\ue73c " # Nerdfont 3.0: nf-dev-python

[rust]
symbol = "\ue7a8 " # Nerdfont 3.0: nf-dev-rust
